### ISSUE TITLE
Error parsing VRCHAT SDK

### ISSUE THREAD

**Issue by PHSYCORO** [FACS01-01/VRC-Hotswap#4]
When I press "VRC Hotswap/Get Latest VRC SDK" i have an error in the console

 " Couldn't parse latest VRC SDK3 version.

UnityEngine.Debug:LogError (object)
VRCHotswap:ErrorMessage (string,System.Exception) (at Assets/VRC Hotswap/Editor/VRCHotswap.cs:226)
VRCHotswap:GetLatestSDK () (at Assets/VRC Hotswap/Editor/VRCHotswap.cs:121) "

Someone know why ?

**Comment by FLASHCAT255** [comment]
It hasn't been updated to work with the new SDKs yet that install to the Packages folder in Unity, it only works on the legacy ones that reside in the Assets folder, if you have any old Unity packages lying around for the old SDK from before the release of the Creator Companion, then you'll be able to use it, the old ones still work.

**Comment by PHSYCORO** [comment]
> It hasn't been updated to work with the new SDKs yet that install to the Packages folder in Unity, it only works on the legacy ones that reside in the Assets folder, if you have any old Unity packages lying around for the old SDK from before the release of the Creator Companion, then you'll be able to use it, the old ones still work.

Oh ok thanks 👍

**Comment by FLASHCAT255** [comment]
No problem! if you per chance need an old version of the SDK that goes into the Assets folder because you can't find it elsewhere, just let me know in the event you trust a unitypackage from a random person on Github (Those particular SDKs aren't officially available for download anymore to my knowledge, the legacy ones on the website were updated to install to the packages folder awhile ago)

**Comment by dankmem** [comment]
> No problem! if you per chance need an old version of the SDK that goes into the Assets folder because you can't find it elsewhere, just let me know in the event you trust a unitypackage from a random person on Github (Those particular SDKs aren't officially available for download anymore to my knowledge, the legacy ones on the website were updated to install to the packages folder awhile ago)

me need :/
NVM, i found another tool to use for hotswapping crashers
ugh but idk if i can use it to upload corrupted bundles or not

**Comment by D1n0ZaWR** [comment]
> No problem! if you per chance need an old version of the SDK that goes into the Assets folder because you can't find it elsewhere, just let me know in the event you trust a unitypackage from a random person on Github (Those particular SDKs aren't officially available for download anymore to my knowledge, the legacy ones on the website were updated to install to the packages folder awhile ago)

me need old sdk :3

**Comment by FACS01-01** [comment]
I haven"t kept this tool updated, and I wouldn't consider it safe to use anymore.
By the meantime look for other hotswap apps. Can't promise to revisit this tool soon.
